# .github/workflows/unittests.yml

name: UnitTests

on:
  push:
      paths:
        - '**.py'
  schedule:
    # Run every Saturday at 01:00
    - cron:  '0 1 * * 5'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
  
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Change Python version in the Pipfile
        run: |
          rm -f Pipfile.lock
          sed -i 's/2.7/${{ matrix.python-version }}/g' Pipfile
      
      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
    
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=200 --statistics
 
      - name: Install latest Kodi Six module from Github repo
        run: |
          wget https://github.com/romanvm/kodi.six/archive/master.zip
          unzip master.zip
          rm -f master.zip
          cd kodi.six-master
          pipenv run python setup.py install
          cd ..
          rm -rf kodi.six-master

      - name: Install routing.py locally
        run: |
          cp build/routing/routing.py $(pipenv --venv)/lib/python2.7/site-packages
      
      - name: Run Unit Tests with pytest
        run: |
          pipenv run pytest
