name: Run Pytest unit tests for every Python file change
on:
  push:
    paths:
      - "**.py"
  schedule:
    # Run every Saturday at 01:00
    - cron: "0 1 * * 5"
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Delete sqlite DB if it exists
        run: |
          rm -f nhk_world_cache.sqlite

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies with pipenv
        run: |
          sudo apt install pipenv
          pipenv install --dev

      - name: Install pre-requisites (Routing)
        env:
          PYTHON_VERSION: '3.12'
        run: |
          pipenv run ./install_packages.sh
        working-directory: build

      - name: Run Unit Tests with pytest
        run: |
          pipenv run pytest
        working-directory: plugin.video.nhkworldtv
